image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt-get update && sudo apt-get upgrade -y
      sudo apt-get install -y build-essential git curl
  - command: |
      echo "Workspace is ready!"

vscode:
  extensions:
    - ms-vscode.cpptools
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint

ports:
  - port: 3000
    onOpen: open-preview
