image:
  file: Dockerfile

tasks:
  - init: |
      sudo apt-get update
  - command: |
      echo "Workspace is ready!"

vscode:
  extensions:
    - ms-vscode.cpptools
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint

ports:
  - port: 3000
    onOpen: open-preview
